#!/usr/bin/env nodejs
var _ = require('lodash');
var moment = require('moment');
var Promise = require('bluebird');
var request = Promise.promisifyAll(require('request'));
var nconf = require('nconf');
var debug = require('debug')("dandelion");
var mongo = require('../lib/mongo');
var various = require('../lib/various');

nconf.argv().env();
nconf.file('settings', { file: '../config/settings.json' });

function composeNEX(fbtrexobj) {
    var content = {
        id: various.hash({
            'href': fbtrexobj.link,
            'type': "original",
        }),
        original: fbtrexobj.link 
    };
    return mongo
        .read("entities", { id: content.id })
        .then(function(exists) {
            if(_.get(exists[0], 'id')  === content.id)
                return null;
            return content;
        });
}

function saveJSON(content) {
    if(!content || !content.id) return;
    return mongo.save("entities", content);
}

function dandelion(partialo, i) {
    var begin = moment();
    return request.postAsync(
        "https://api.dandelion.eu/datatxt/nex/v1/",
        { form: {
            token: "f488305e75dc432c853a461e54022b63",
            url: partialo.original
        } }
        ).then(function (response, body) {
            // response.headers['x-dl-units-reset']
            debug("%d) Tested %s, units left %d", i,
                    partialo.original,
                    response.headers['x-dl-units-left']);
            return _.extend(partialo, JSON.parse(response.body));
        })
        .catch(function(error) {
            debug("Error with %s: %s", partialo.original, error);
        })
        .tap(function() {
            debug("Dandelion get completed in %d seconds",
                moment.duration(moment() - begin).asSeconds());
        })
        .then(saveJSON)
}

if(!nconf.get('api'))
    throw new Error("api");

var SERVER_API_URL = nconf.get('api');
debug("API endpoint %s", SERVER_API_URL);

var bigbang = moment();
return various
    .loadJSONurl(SERVER_API_URL)
    .tap(function(urls) {
        debug("retrieved %d urls", _.size(urls));
    })
    .map(composeNEX, { concurrency: 1 })
    .then(_.compact)
    .tap(function(xxx) {
        debug("new urls %d, in %d seconds", _.size(xxx),
            moment.duration(moment() - bigbang).asSeconds());
    })
    .map(dandelion, { concurrency: 1 })
    .tap(function(xxx) {
        debug("Fetched %d resources in %d seconds", _.size(xxx),
            moment.duration(moment() - bigbang).asSeconds());
    });

/*
> JSON.parse(response.body)
{ time: 73,
  annotations: 
   [ { start: 0,
       end: 9,
       spot: 'Australia',
       confidence: 0.7744,
       id: 4689264,
       title: 'Australia',
       uri: 'http://en.wikipedia.org/wiki/Australia',
       label: 'Australia' },
     { start: 17,
       end: 30,
       spot: 'asylum seeker',
       confidence: 0.8465,
       id: 276005,
       title: 'Asylum seeker',
       uri: 'http://en.wikipedia.org/wiki/Asylum_seeker',
       label: 'Asylum seekers' },
     { start: 121,
       end: 150,
       spot: 'Manus Island detention centre',
       confidence: 0.7615,
       id: 42695057,
       title: 'Manus Regional Processing Centre',
       uri: 'http://en.wikipedia.org/wiki/Manus_Regional_Processing_Centre',
       label: 'Manus Regional Processing Centre' },
     { start: 154,
       end: 170,
       spot: 'Papua New Guinea',
       confidence: 0.8667,
       id: 22943,
       title: 'Papua New Guinea',
       uri: 'http://en.wikipedia.org/wiki/Papua_New_Guinea',
       label: 'Papua New Guinea' },
     { start: 253,
       end: 260,
       spot: 'REUTERS',
       confidence: 0.7967,
       id: 18998750,
       title: 'Reuters',
       uri: 'http://en.wikipedia.org/wiki/Reuters',
       label: 'Reuters' },
     { start: 261,
       end: 269,
       spot: 'CANBERRA',
       confidence: 0.8076,
       id: 51983,
       title: 'Canberra',
       uri: 'http://en.wikipedia.org/wiki/Canberra',
       label: 'Canberra' },
     { start: 271,
       end: 278,
       spot: 'Reuters',
       confidence: 0.7958,
       id: 18998750,
       title: 'Reuters',
       uri: 'http://en.wikipedia.org/wiki/Reuters',
       label: 'Reuters' },
     { start: 282,
       end: 291,
       spot: 'Australia',
       confidence: 0.7729,
       id: 4689264,
       title: 'Australia',
       uri: 'http://en.wikipedia.org/wiki/Australia',
       label: 'Australia' },
     { start: 310,
       end: 324,
       spot: 'asylum seekers',
       confidence: 0.7111,
       id: 276005,
       title: 'Asylum seeker',
       uri: 'http://en.wikipedia.org/wiki/Asylum_seeker',
       label: 'Asylum seekers' },
     { start: 418,
       end: 425,
       spot: 'Reuters',
       confidence: 0.8037,
       id: 18998750,
       title: 'Reuters',
       uri: 'http://en.wikipedia.org/wiki/Reuters',
       label: 'Reuters' },
     { start: 436,
       end: 444,
       spot: 'Canberra',
       confidence: 0.799,
       id: 51983,
       title: 'Canberra',
       uri: 'http://en.wikipedia.org/wiki/Canberra',
       label: 'Canberra' },
     { start: 488,
       end: 504,
       spot: 'Papua New Guinea',
       confidence: 0.8819,
       id: 22943,
       title: 'Papua New Guinea',
       uri: 'http://en.wikipedia.org/wiki/Papua_New_Guinea',
       label: 'Papua New Guinea' },
     { start: 507,
       end: 519,
       spot: 'Manus Island',
       confidence: 0.8799,
       id: 308069,
       title: 'Manus Island',
       uri: 'http://en.wikipedia.org/wiki/Manus_Island',
       label: 'Manus' },
     { start: 555,
       end: 568,
       spot: 'island nation',
       confidence: 0.7002,
       id: 525000,
       title: 'Island country',
       uri: 'http://en.wikipedia.org/wiki/Island_country',
       label: 'Island nation' },
     { start: 572,
       end: 577,
       spot: 'Nauru',
       confidence: 0.9084,
       id: 21302,
       title: 'Nauru',
       uri: 'http://en.wikipedia.org/wiki/Nauru',
       label: 'Nauru' },
     { start: 604,
       end: 618,
       spot: 'refugee status',
       confidence: 0.7163,
       id: 45547,
       title: 'Refugee',
       uri: 'http://en.wikipedia.org/wiki/Refugee',
       label: 'Refugee' },
     { start: 653,
       end: 665,
       spot: 'resettlement',
       confidence: 0.6272,
       id: 221773,
       title: 'Human migration',
       uri: 'http://en.wikipedia.org/wiki/Human_migration',
       label: 'Migration' },
     { start: 709,
       end: 716,
       spot: 'Reuters',
       confidence: 0.8113,
       id: 18998750,
       title: 'Reuters',
       uri: 'http://en.wikipedia.org/wiki/Reuters',
       label: 'Reuters' },
     { start: 725,
       end: 733,
       spot: 'Refugees',
       confidence: 0.6945,
       id: 45547,
       title: 'Refugee',
       uri: 'http://en.wikipedia.org/wiki/Refugee',
       label: 'Refugee' },
     { start: 741,
       end: 754,
       spot: 'United States',
       confidence: 0.7533,
       id: 3434750,
       title: 'United States',
       uri: 'http://en.wikipedia.org/wiki/United_States',
       label: 'United States' },
     { start: 793,
       end: 798,
       spot: 'Nauru',
       confidence: 0.9048,
       id: 21302,
       title: 'Nauru',
       uri: 'http://en.wikipedia.org/wiki/Nauru',
       label: 'Nauru' },
     { start: 866,
       end: 875,
       spot: 'Australia',
       confidence: 0.7799,
       id: 4689264,
       title: 'Australia',
       uri: 'http://en.wikipedia.org/wiki/Australia',
       label: 'Australia' },
     { start: 906,
       end: 911,
       spot: 'Manus',
       confidence: 0.7462,
       id: 308069,
       title: 'Manus Island',
       uri: 'http://en.wikipedia.org/wiki/Manus_Island',
       label: 'Manus' },
     { start: 966,
       end: 974,
       spot: 'Canberra',
       confidence: 0.8076,
       id: 51983,
       title: 'Canberra',
       uri: 'http://en.wikipedia.org/wiki/Canberra',
       label: 'Canberra' },
     { start: 986,
       end: 1004,
       spot: 'immigration policy',
       confidence: 0.6497,
       id: 1100670,
       title: 'Immigration to Australia',
       uri: 'http://en.wikipedia.org/wiki/Immigration_to_Australia',
       label: 'Immigration to Australia' },
     { start: 1006,
       end: 1020,
       spot: 'asylum seekers',
       confidence: 0.7287,
       id: 276005,
       title: 'Asylum seeker',
       uri: 'http://en.wikipedia.org/wiki/Asylum_seeker',
       label: 'Asylum seekers' },
     { start: 1056,
       end: 1065,
       spot: 'Australia',
       confidence: 0.7751,
       id: 4689264,
       title: 'Australia',
       uri: 'http://en.wikipedia.org/wiki/Australia',
       label: 'Australia' },
     { start: 1097,
       end: 1102,
       spot: 'Manus',
       confidence: 0.7507,
       id: 308069,
       title: 'Manus Island',
       uri: 'http://en.wikipedia.org/wiki/Manus_Island',
       label: 'Manus' },
     { start: 1107,
       end: 1112,
       spot: 'Nauru',
       confidence: 0.8982,
       id: 21302,
       title: 'Nauru',
       uri: 'http://en.wikipedia.org/wiki/Nauru',
       label: 'Nauru' },
     { start: 1164,
       end: 1173,
       spot: 'Australia',
       confidence: 0.7687,
       id: 4689264,
       title: 'Australia',
       uri: 'http://en.wikipedia.org/wiki/Australia',
       label: 'Australia' },
     { start: 1220,
       end: 1233,
       spot: 'United States',
       confidence: 0.734,
       id: 3434750,
       title: 'United States',
       uri: 'http://en.wikipedia.org/wiki/United_States',
       label: 'United States' },
     { start: 1266,
       end: 1273,
       spot: 'refugee',
       confidence: 0.7089,
       id: 45547,
       title: 'Refugee',
       uri: 'http://en.wikipedia.org/wiki/Refugee',
       label: 'Refugee' },
     { start: 1291,
       end: 1301,
       spot: 'Washington',
       confidence: 0.6698,
       id: 108956,
       title: 'Washington, D.C.',
       uri: 'http://en.wikipedia.org/wiki/Washington%2C_D.C.',
       label: 'Washington, D.C.' },
     { start: 1306,
       end: 1314,
       spot: 'Canberra',
       confidence: 0.7738,
       id: 51983,
       title: 'Canberra',
       uri: 'http://en.wikipedia.org/wiki/Canberra',
       label: 'Canberra' },
     { start: 1321,
       end: 1335,
       spot: 'U.S. President',
       confidence: 0.7459,
       id: 24113,
       title: 'President of the United States',
       uri: 'http://en.wikipedia.org/wiki/President_of_the_United_States',
       label: 'President' },
     { start: 1336,
       end: 1348,
       spot: 'Donald Trump',
       confidence: 0.8947,
       id: 4848272,
       title: 'Donald Trump',
       uri: 'http://en.wikipedia.org/wiki/Donald_Trump',
       label: 'Donald Trump' },
     { start: 1529,
       end: 1537,
       spot: 'refugees',
       confidence: 0.6696,
       id: 45547,
       title: 'Refugee',
       uri: 'http://en.wikipedia.org/wiki/Refugee',
       label: 'Refugee' },
     { start: 1585,
       end: 1595,
       spot: 'government',
       confidence: 0.6403,
       id: 50741788,
       title: 'Government',
       uri: 'http://en.wikipedia.org/wiki/Government',
       label: 'Government' },
     { start: 1673,
       end: 1680,
       spot: 'Kurdish',
       confidence: 0.8152,
       id: 17068,
       title: 'Kurds',
       uri: 'http://en.wikipedia.org/wiki/Kurds',
       label: 'Kurdish' },
     { start: 1700,
       end: 1705,
       spot: 'Manus',
       confidence: 0.7284,
       id: 308069,
       title: 'Manus Island',
       uri: 'http://en.wikipedia.org/wiki/Manus_Island',
       label: 'Manus' },
     { start: 1730,
       end: 1744,
       spot: 'refugee status',
       confidence: 0.7077,
       id: 45547,
       title: 'Refugee',
       uri: 'http://en.wikipedia.org/wiki/Refugee',
       label: 'Refugee' },
     { start: 1798,
       end: 1807,
       spot: 'Australia',
       confidence: 0.7516,
       id: 4689264,
       title: 'Australia',
       uri: 'http://en.wikipedia.org/wiki/Australia',
       label: 'Australia' },
     { start: 1828,
       end: 1842,
       spot: 'U.S. president',
       confidence: 0.7537,
       id: 24113,
       title: 'President of the United States',
       uri: 'http://en.wikipedia.org/wiki/President_of_the_United_States',
       label: 'President' },
     { start: 1843,
       end: 1855,
       spot: 'Barack Obama',
       confidence: 0.8986,
       id: 534366,
       title: 'Barack Obama',
       uri: 'http://en.wikipedia.org/wiki/Barack_Obama',
       label: 'Barack Obama' },
     { start: 1876,
       end: 1889,
       spot: 'United States',
       confidence: 0.7385,
       id: 3434750,
       title: 'United States',
       uri: 'http://en.wikipedia.org/wiki/United_States',
       label: 'United States' },
     { start: 1916,
       end: 1930,
       spot: 'asylum seekers',
       confidence: 0.7268,
       id: 276005,
       title: 'Asylum seeker',
       uri: 'http://en.wikipedia.org/wiki/Asylum_seeker',
       label: 'Asylum seekers' },
     { start: 1939,
       end: 1942,
       spot: 'PNG',
       confidence: 0.7638,
       id: 22943,
       title: 'Papua New Guinea',
       uri: 'http://en.wikipedia.org/wiki/Papua_New_Guinea',
       label: 'Papua New Guinea' },
     { start: 1947,
       end: 1952,
       spot: 'Nauru',
       confidence: 0.9084,
       id: 21302,
       title: 'Nauru',
       uri: 'http://en.wikipedia.org/wiki/Nauru',
       label: 'Nauru' },
     { start: 1967,
       end: 1976,
       spot: 'Australia',
       confidence: 0.782,
       id: 4689264,
       title: 'Australia',
       uri: 'http://en.wikipedia.org/wiki/Australia',
       label: 'Australia' },
     { start: 2023,
       end: 2031,
       spot: 'refugees',
       confidence: 0.6872,
       id: 45547,
       title: 'Refugee',
       uri: 'http://en.wikipedia.org/wiki/Refugee',
       label: 'Refugee' },
     { start: 2033,
       end: 2042,
       spot: 'Australia',
       confidence: 0.7749,
       id: 4689264,
       title: 'Australia',
       uri: 'http://en.wikipedia.org/wiki/Australia',
       label: 'Australia' },
     { start: 2096,
       end: 2104,
       spot: 'refugees',
       confidence: 0.6666,
       id: 45547,
       title: 'Refugee',
       uri: 'http://en.wikipedia.org/wiki/Refugee',
       label: 'Refugee' },
     { start: 2166,
       end: 2171,
       spot: 'Nauru',
       confidence: 0.9047,
       id: 21302,
       title: 'Nauru',
       uri: 'http://en.wikipedia.org/wiki/Nauru',
       label: 'Nauru' },
     { start: 2279,
       end: 2293,
       spot: 'United Nations',
       confidence: 0.8245,
       id: 31769,
       title: 'United Nations',
       uri: 'http://en.wikipedia.org/wiki/United_Nations',
       label: 'United Nations' },
     { start: 2298,
       end: 2310,
       spot: 'human rights',
       confidence: 0.7481,
       id: 13831,
       title: 'Human rights',
       uri: 'http://en.wikipedia.org/wiki/Human_rights',
       label: 'Human rights' },
     { start: 2340,
       end: 2352,
       spot: 'sexual abuse',
       confidence: 0.7188,
       id: 7397019,
       title: 'Sexual abuse',
       uri: 'http://en.wikipedia.org/wiki/Sexual_abuse',
       label: 'Sexual abuse' },
     { start: 2358,
       end: 2370,
       spot: 'self-harming',
       confidence: 0.7087,
       id: 150374,
       title: 'Self-harm',
       uri: 'http://en.wikipedia.org/wiki/Self-harm',
       label: 'Self-harm' } ],
  lang: 'en',
  langConfidence: 1,
  text: 'Australia pushes asylum seeker transfer in bid to close controversial camp\nSecur... (length: 2371)',
  url: 'http://af.reuters.com/article/worldNews/idAFKBN1CF1FE',
  timestamp: '2017-10-12T14:33:30.014' }

  */
