version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017"
    networks:
      - backend
  elastic:
    ports:
      - "9200"
      - "9300"
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.elastic
    command:
      - bash support/elastic/setup.sh
  fbtrex:
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - mongo
      - elastic
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile

networks:
  backend:
