module.exports = {
    images: require('../images'),
    interactions: require('../interactions'),
    attributions: require('../attributions'),
    shared: require('../shared'),
    linkontime: require('../linkontime'),
    feed_id: require('../feed_id'),
    'data-ad-preview': require('../data-ad-preview'),
    usertext: require('../usertext'),
    reasons: require('../reasons'),
    arbitrary: require('../arbitrary'),
    commentable: require('../commentable'),
    external: require('../external'),
    event: require('../event'),
    // regexp: require('../regexp'),
    opengraph: require('../opengraph'),
    video: require('../video'),
};
